### ISSUE TITLE
Issue with multiplayer 

### ISSUE THREAD

**Issue by adamkorle** [Sartaq12/WaterInteractionPlugin#9]
In the editor, while playing as a listen server with one client, the host's oceanology water appearance changes upon the client's joining. and the client's view remains unaffected. 

You can see in the attached image, the client's water looks fine but the host's water looks completely different. You can recreate the bug in the test map and play as listen server. 

![image](https://user-images.githubusercontent.com/7088160/236355565-9290e2c3-d18b-4ce2-85f3-bb210ad74c66.png)

**Comment by Sartaq12** [comment]
Yes, there can only be one NinjaLive area water actor present in the level, otherwise this happens, to insure that happens you can use this: 
![image](https://user-images.githubusercontent.com/37218094/236781650-f876c507-f8dd-4135-ae9c-a304820a4455.png)
then the ninja live child actor will only spawn on each client locally, which is how it should be.
Result:
![image](https://user-images.githubusercontent.com/37218094/236781755-511ac2f3-5de7-4a9f-9236-df0858193275.png)

So instead of having them on the components view I'll have to add them in the begin play event to make the plugin multiplayer-ready.

**Comment by Sartaq12** [comment]
@adamkorle I've opened a PR for fixing this, could you please review it that it works for you?

**Comment by adamkorle** [comment]
@Sartaq12 Just pulled your fixes and looks like it's working now! Confirmed by removing the water interaction actors from the component's view and adding the ninja live child actor BP logic to my pawns. no more issues after. 
Thank you again for looking into this!
